questions_1 = {"Which of the following animals can run the fastest?": "A",
               "What does the term “SOS” commonly stand for?": "D",
               "Which company is known for publishing the Mario video game?": "B",
               "What is the rarest type of blood in the human body?": "A",
               "What is the name of this symbol: ¶": "D",
               "Which of the following is not an international organisation?": "D",
               "What is the speed of sound?": "B",
               "In total, how many novels were written by the Bronte sisters?": "D",
               "What was the first country to use tanks in combat during World War I?": "C",
               "Goulash is a type of beef soup in which country?": 'A',
               "Which of the following songs was the top-selling hit in 2019?": "A",
               "We often use sodium bicarbonate in the kitchen. What is its other name?": "D",
               "Which was the first film by Disney to be produced in colour?": "C",
               "Cu is the chemical symbol for which element?": "B",
               "In the series “Game of Thrones”, Winterfell is the ancestral home of which family?": "B",
               }

answers_1 = [["A. Cheetah", "B. Leopard", "C. Tiger", "D. Lion"],
             ["A. Save Our Sheep", "B. Save Our Ship", "C. Save Our Seal", "D. Save Our Souls"],
             ["A. Xbox", "B. Nintendo", "C. SEGA", "D. Electronic Arts"],
             ["A. AB negative", "B. O positive", "C. B negative", "D. A positive"],
             ["A. Biltong", "B. Fermata", "C. Interrobang", "D. Pilcrow"],
             ["A.FIFA", "B.NATO", "C.ASEAN", "D.FBI"],
             ["A. 120 km/h", "B. 1,200 km/h", "C. 400 km/h", "D. 700 km/h"],
             ["A.4", "B.5", "C.6", "D.7"],
             ["A. France", "B. Japan", "C. Britain", "D. Germany"],
             ["A. Hungary", "B. Czech Republic", "C. Slovakia", "D. Ireland"],
             ["A. Someone You Loved", "B. Old Town Road", "C. I Don’t Care", "D. Bad Guy"],
             ["A. Vinegar", "B. Sugar", "C. Salt", "D. Baking soda"],
             ["A. Toy Story", "B. Sleeping Beauty", "C. Snow White and the Seven Dwarfs", "D. Cinderella"],
             ["A. Oxygen", "B. Copper", "C. Zinc", "D. Helium"],
             ["A. The Lannisters", "B. The Starks", "C. The Tully’s", "D. The Targaryens"]]

money_list = [100, 200, 300, 500, 1000, 2000, 4000, 8000, 16000, 32000, 64000, 125000, 250000, 500000, 1000000]
